// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text" `
	UserID string `json:"userId" `
}

type Todo struct {
	ID   string `json:"id" `
	Text string `json:"text" gorm:"column:text"`
	Done bool   `json:"done" gorm:"column:is_done"`
	User *User  `json:"user" `
}

type User struct {
	ID   string `json:"id" `
	Name string `json:"name" `
}
